### ISSUE TITLE
Could this be made to work with an Arduino Pro Micro?

### ISSUE THREAD

**Issue by prashcr** [juancgarcia/HID-Relay#2]
I'm new to electronics and I have a bunch of spare pro micros so I was wondering if I could use those instead.

**Comment by juancgarcia** [comment]
It's seems not all of the pin assignments line up between the pro mini and pro micro

SS, MOSI, MISO, SCK are 10,11,12,13 on the mini and 10,16,14,15 on the micro. I think it may be possible to remap these pins in your sketch, but you'll need to look into the usb host controller documentation to know for sure.

Of more concern is one pin where the host controller expects reset, the micro provides gnd. If connected without modification, I believe this would cause the host controller to constantly boot loop. This will require physically cutting a trace on the host shield and adding a jumper wire to the proper reset pin.

![usb host shield](https://www.circuitsathome.com/wp/wp-content/uploads/2011/02/uhm11_manual.jpg)

![pro micro](http://www.pighixxx.com/test/wp-content/uploads/2016/07/pro_micro_pinout_v1_0_red.png)

![pro mini](http://www.pighixxx.com/test/wp-content/uploads/2016/07/promini_final.png)

**Comment by prashcr** [comment]
Thank you so much for the detailed explanation.

With some further research, it seems an alternative to connecting the pro micro's reset to the host shield's reset would be to connect the pro micro's vcc to the host shield's reset instead.

Example with Pro Micro: https://geekhack.org/index.php?topic=80421.0  
Example with Teensy: https://www.pjrc.com/teensy/td_libs_USBHostShield.html

**Comment by juancgarcia** [comment]
That looks like it might work then.
