### ISSUE TITLE
Powering Keyboard externally?

### ISSUE THREAD

**Issue by schlegp** [juancgarcia/HID-Relay#3]
I know this isn't an issue with the project, but I don't know where else to ask.
I am a beginner in the whole arduino scene and decided to use this project to do my first steps.
Currently, I have the problem that my mechanical keyboard won't work with this. Cheap 5$ Keyboards work, but not my mechanical.
I suspect it is insufficient power to the keyboard, but I have no way to find out.
Does anyone know, if it is possible to power the keyboard externally from a 5V source?

**Comment by juancgarcia** [comment]
I had a similar issue with one of my mechanical keyboards. The solution I found was to trigger the arduino's reset button a second or two after power was applied.

I'm not entirely sure why it works but I'm assuming that the keyboard's controller needs more time to power up and isn't ready to talk to the USB host module immediately. The theory is resetting the arduino makes the initial setup try again once the keyboard has fully powered up.
