### ISSUE TITLE
USB HID directly to BT

### ISSUE THREAD

**Issue by FSP2692** [juancgarcia/HID-Relay#4]
Hello.
I am not into hardwares and arduino stuff, but I was really interested by the video you made on youtube about HID Relay.
I am currently looking for a way to transmit USB HID reports (signals) directly to the PC, so there is minimal latency created.
I have found that USB HID signals and Bluetooth HID signals are almost identical, so I am wondering if directly feeding the signal to the pc via bluetooth be done.
If it cannot be done using bluetooth, I would like to build a simple dongle instead of bluetooth, so the signal will go like:

PC---Dongle---RF Signal---Transceiver---USB Device.

So, it's basically a wireless USB cable.
Are you interested in this project? I think this might help your channel

**Comment by FSP2692** [comment]
Ah, mispressed the submit button.

I think this might help your youtube channel since I found a lot of people who would like to do the same thing on internet.

Thanks!

**Comment by FSP2692** [comment]
Hmm, I looked over the Bluetooth HID section of USB Host Shield library, and it seems like that there is no "translating" process that converts USB HID signals into BT HID signals?
Not really sure, but what does Arduino exactly do in HID Relay? Converting USB signals to serial signal then feeding it to the HC-05?

Sorry for asking questions that can be easily answered by reading articles about Arduino, I'm just too eager to find a way to get this working.

**Comment by juancgarcia** [comment]
Basically yes, that's what my project does. The HID payloads are read from the keyboard, mouse, etc and serialized to a format the Bluetooth module can read as keystrokes or mouse moves. 

The catch is that this project can't generically send any HID payloads. The Bluetooth module makes new HID messages from the translated serial messages. Also the module had to be configured as a specific device (keyboard, mouse, gamepad, etc) to announce to the PC.

This configuration can't work as a wireless USB cable, it just relays input messages.

**Comment by FSP2692** [comment]
@juancgarcia
I now get it, thank you for the explanation.

I figured that I will build a HID Relay and learn about how arduino works in the process.

My final goal still is to build a wireless usb cable, though.

Have a good day!
